### ISSUE TITLE
1.B. Vision / White Paper: full final version

### ISSUE THREAD

**Issue by RizzeKnight** [step21/fosshealth#1]
Mentor feedback (rainbowday 13:11)
I really like the problem statement (and the link community quality and security considerations). Great also to check prior efforts.
**However, how your solution would solve this problem is not clear. Mostly a new leaderboard or by using identity?**
**-> Prioritize clarifying their more critical take here!**

[FOSS-Health_White-Paper.odt](https://github.com/step21/fosshealth/files/15441630/FOSS-Health_White-Paper.odt)
**-> MOVED latest version (updated by Flo) to 
https://office.ethberlin.org/doc/#/2/doc/edit/zlvdG1Keb48HPGiEjiOsg8cE/

Outline / broader vision to realize; describe problems, solutions.
Design included, or at least forms basis for separate (functional) design document.

**Comment by RizzeKnight** [comment]
@step21 could you please review/revise this document and ideally also write a very brief introduction, real quick?
@ryndon could you please review/revise (overall), and also fill out the rest of the 'design' section?
Thanks!
@theotow FYI

**Comment by step21** [comment]
[FOSS-Health_White-Paper.odt](https://github.com/step21/fosshealth/files/15443501/FOSS-Health_White-Paper.odt)
@RizzeKnight done. Can you also reflect changes in the codimd document? I added the introduction but also made some changes esp. at the end I toned it down a bit. Also re metrics necessary for identity projects - that's not aligned with my goals and I don't even know if there are such metrics, so I don't want to include it. It's IMO perfectly fine to treat the identity crisis as an ecosystem crisis that doesn't necessarily have anything to do with identity in the sense of identification.

Re mentor feedback, it's not 'just' a leaderboard, this is just one idea for an interface for easy discovery and comparison.

**Comment by RizzeKnight** [comment]
**ATTENTION: moved latest version to 
https://office.ethberlin.org/doc/#/2/doc/edit/zlvdG1Keb48HPGiEjiOsg8cE/.**

**Comment by RizzeKnight** [comment]
Full/complete version DONE
