### ISSUE TITLE
3.C. Frontend/Design

### ISSUE THREAD

**Issue by RizzeKnight** [step21/fosshealth#12]
_(might be a duplicate, could have sworn I already created this - unable to verify though)_

1. At least provide Design for (intended) application e.g. by way of wireframes/mockups
2. Insofar possible BUIDL frontend

**See also / keep aligned with #7 please.**

**Comment by RizzeKnight** [comment]
@ryndon please take the lead on this & include others as you see fit
@step21 @theotow FYI

**Comment by ryndon** [comment]
A possible reference for design layout inspiration: https://l2beat.com/scaling/summary

**Comment by RizzeKnight** [comment]
@YYBer this is basically yours now - please post all updates here for tracking purposes, thanks!
(note: maybe Ryndon and especially @taha-be for design, Manuel for backend/data insofar you need)

**Comment by RizzeKnight** [comment]
https://drive.google.com/drive/folders/13E7RoFA3-PXIXOZeOPfceLslRd0DjuYP @YYBer FYI from @taha-be

**Comment by YYBer** [comment]
index page updated, some frontend issues need to fix

**Comment by RizzeKnight** [comment]
Static page completed
