### ISSUE TITLE
2.D. Exploring data sourcing 

### ISSUE THREAD

**Issue by RizzeKnight** [step21/fosshealth#6]
Crawling / extraction / scraping?

**Comment by RizzeKnight** [comment]
@theotow yours to 'lead' now - please post your thoughts/conclusions on this here & close out issue ASAP, thanks (we can always keep refering back to hackMD if need be).

**Comment by RizzeKnight** [comment]
@step21 please support Manuel, also see previous comment; close out with clear comment please. 

Please factor in where we get our data from:
1. Now (hackathon)
2. Mid-long term (potentially/ideally)

**Comment by theotow** [comment]
Now:

- CHAOSS
- oss-red-flag-checker
- github api
- OpenSauced

Mid-long term:
- own scraper
- kaggle data
