### ISSUE TITLE
3.A. Define functions

### ISSUE THREAD

**Issue by RizzeKnight** [step21/fosshealth#7]
Maybe also prioritize.
If need be / preferred: create separate (functional) design document.

- Sorted table (‘leaderboard’) of (Web3) FOSS Projects 
- Aggregate ‘Health’ score (cannot build/implement - not qualified), maybe 'Impact'
- Specific metrics (see #3 ), specific 'roll-ups' / aggregates
- SORT (column)
- Compare?

Out of Hackathon scope / ‘stretch goals’:
- Filters
- 'Weighting’
- Update ‘Health’ & sorting regularly
- Search
- Detail page (click on project name) - URL e.g. GH/website on top, multiple additional (aggregated) metrics (TBD)

**Comment by RizzeKnight** [comment]
@ryndon please review / update.
@step21 @theotow FYI (feel free to also review/revise, of course, but suggest Ryndon takes the lead on this)

**Comment by ryndon** [comment]
(AGGREGATED -> #4 )

Data to Pull from GitHub and how it maps to table Columns.

Name
Releases
Days Since Last Last Interaction
Number of open issues
Responsiveness = issues open time, review timr
Interest = watcher, contributors, forks

**Comment by RizzeKnight** [comment]
Discussed w/Ryndon, DONE
