### ISSUE TITLE
4.A. Presentation

### ISSUE THREAD

**Issue by RizzeKnight** [step21/fosshealth#9]
Quick few slides on idea, vision, work done, further outlook. Main aspect: overall project value.

Cryptpad (ETHBerlin Office): https://office.ethberlin.org/presentation/#/2/presentation/edit/i8wjxIZWFeQ-EX2sNXux94Qe/

**Comment by ryndon** [comment]
Slide 1: Our project name, brand, logo.
Slide 2: The problem
Slide 3: Our solution
Slide 4: How it works / demo / user experience
Slide 5: Use cases and/or target market
Slide 6: Our team
Slide 7: End

**Comment by RizzeKnight** [comment]
Input: https://office.ethberlin.org/doc/#/2/doc/edit/zlvdG1Keb48HPGiEjiOsg8cE/
Also https://hackmd.okfn.de/gZi7aAdoQ7a1tUrExYR_Sw?view

**Comment by RizzeKnight** [comment]
@ryndon all you now. Updated https://office.ethberlin.org/presentation/#/2/presentation/edit/i8wjxIZWFeQ-EX2sNXux94Qe/ with a lot, if not all of the base things. Please review & update/finalize. Maybe decrease text (-> notes), subtitute images. Thanks!

**Comment by RizzeKnight** [comment]
Read only for latest version (updated by Ryndon): https://office.ethberlin.org/presentation/#/2/presentation/view/LnasAoejwO2p6+0bNknOZnfxg7a29RA-fcND30-TEAc/
